import { test, expect } from '@playwright/test';
import { createServer, type Server } from 'node:http';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { once } from 'node:events';
import { openStore } from '../server/store.mjs';
import { createApp } from '../server/app.mjs';
import { saveAccount } from '../server/auth.mjs';
import AxeBuilder from '@axe-core/playwright';

let server: Server, db: ReturnType<typeof openStore>, origin: string, dir: string;
const password = randomBytes(24).toString('base64url');
test.beforeAll(async () => {
  dir = mkdtempSync(join(tmpdir(), 'club-browser-'));
  db = openStore(join(dir, 'club.sqlite'));
  for (const role of ['student', 'teacher', 'admin']) await saveAccount(db, { role, email: `${role}@example.test`, name: role, password });
  server = createServer().listen(0, '127.0.0.1');
  await once(server, 'listening');
  const address = server.address();
  if (!address || typeof address === 'string') throw new Error('No se pudo abrir el servidor de prueba');
  origin = `http://127.0.0.1:${address.port}`;
  server.on('request', createApp({ db, origin, production: false }));
});
test.afterAll(async () => {
  if (server) await new Promise<void>((resolve) => server.close(() => resolve()));
  db?.close();
  if (dir) rmSync(dir, { recursive: true, force: true });
});

test('el servidor publica rutas SEO y el sitemap sin JavaScript', async ({ page }) => {
  const school = await page.request.get(`${origin}/escuela`);
  expect(school.status()).toBe(200);
  const html = await school.text();
  expect(html).toContain('<h1>Escuela Club Palentino</h1>');
  expect(html).toContain(`rel="canonical" href="${origin}/escuela"`);
  const sitemap = await page.request.get(`${origin}/sitemap.xml`);
  expect(await sitemap.text()).toContain(`<loc>${origin}/escuela</loc>`);
  await page.goto(`${origin}/escuela`);
  await expect(page.getByRole('heading', { name: 'Escuela Club Palentino', exact: true })).toBeVisible();
});

test('servidor real: tres accesos, subida, descarga, cookie y permisos', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`${origin}/#/acceso-equipo`);
  await page.getByLabel('Correo electrónico').fill('teacher@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Subir material', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Noticias', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Usuarios', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Subir material', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Título del material').fill('Material privado real');
  await dialog.getByLabel('Tema', { exact: true }).fill('Finales');
  await dialog.locator('input[type=file]').setInputFiles({ name: 'finales.txt', mimeType: 'text/plain', buffer: Buffer.from('Ejercicio privado') });
  await dialog.getByRole('button', { name: 'Subir material', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  expect(await page.evaluate(() => document.cookie)).not.toContain('club-session');
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain(password);
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await expect(page.getByLabel('Contraseña de las clases')).toBeVisible();
  await page.getByLabel('Contraseña de las clases').fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page).toHaveURL(/#\/aula$/);
  await page.goto(`${origin}/#/aula/iniciacion`);
  await expect(page.getByRole('heading', { name: 'Material privado real' })).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar Material privado real' }).click();
  expect((await download).suggestedFilename()).toBe('finales.txt');
  await page.goto(`${origin}/#/panel`);
  await expect(page.getByRole('heading', { name: 'Este espacio es para el profesorado.' })).toBeVisible();
  await page.goto(`${origin}/#/aula`);
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await expect(page.getByLabel('Contraseña de las clases')).toBeVisible();
  await page.goto(`${origin}/#/acceso-equipo`);
  await page.getByLabel('Correo electrónico').fill('admin@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Noticias', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Torneos', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Noticias', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('servidor real: una sesión revocada retira el contenido privado en el siguiente acceso', async ({ page }) => {
  await page.goto(`${origin}/#/acceso`);
  await page.getByLabel('Contraseña de las clases').fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page).toHaveURL(/#\/aula$/);
  db.prepare('DELETE FROM sessions').run();
  await page.getByRole('link', { name: /LOS PRIMEROS PASOS/ }).click();
  await expect(page.getByLabel('Contraseña de las clases')).toBeVisible();
  await expect(page.getByRole('button', { name: /Descargar/ })).toHaveCount(0);
});

test('usuarios: altas, permisos, contraseñas, bajas y reactivación desde el panel', async ({ page }, testInfo) => {
  test.setTimeout(60000);
  await page.goto(`${origin}/#/acceso-equipo`);
  await page.getByLabel('Correo electrónico').fill('admin@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Usuarios', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Usuarios del equipo' })).toBeVisible();
  await page.getByRole('button', { name: 'Nuevo usuario', exact: true }).click();
  const dialog = page.getByRole('dialog');
  const current = dialog.getByLabel('Tu contraseña actual de administrador');
  await dialog.getByLabel('Nombre', { exact: true }).fill('Ana del Club');
  await dialog.getByLabel('Correo electrónico').fill('ana@example.test');
  await dialog.getByLabel('Nueva contraseña', { exact: true }).fill(password);
  await dialog.getByLabel('Repite la nueva contraseña').fill(password);
  await current.fill('incorrect-password');
  await dialog.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('Tu contraseña actual no es correcta');
  await expect(current).toHaveValue('');
  await expect(dialog.getByLabel('Nueva contraseña', { exact: true })).toHaveValue('');
  await expect(dialog.getByLabel('Nombre', { exact: true })).toHaveValue('Ana del Club');
  await dialog.getByLabel('Nueva contraseña', { exact: true }).fill(password);
  await dialog.getByLabel('Repite la nueva contraseña').fill(password);
  await current.fill(password);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await dialog.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const card = page.getByRole('article', { name: 'Ana del Club', exact: true });
  await expect(card).toContainText('Profesor');
  await card.getByRole('button', { name: 'Editar Ana del Club' }).click();
  await dialog.getByRole('combobox', { name: 'Rol', exact: true }).selectOption('admin');
  await current.fill(password);
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(card).toContainText('Administrador');
  await card.getByRole('button', { name: 'Cambiar contraseña de Ana del Club' }).click();
  const replacement = randomBytes(24).toString('base64url');
  await dialog.getByLabel('Nueva contraseña', { exact: true }).fill(replacement);
  await dialog.getByLabel('Repite la nueva contraseña').fill(replacement);
  await current.fill(password);
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(dialog).not.toBeVisible();
  await card.getByRole('button', { name: 'Desactivar Ana del Club' }).click();
  await current.fill(password);
  await dialog.getByRole('button', { name: 'Desactivar cuenta' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(card).toContainText('Desactivada');
  await page.reload();
  await page.getByRole('button', { name: 'Usuarios', exact: true }).click();
  await expect(card).toContainText('Desactivada');
  await card.getByRole('button', { name: 'Reactivar Ana del Club' }).click();
  await current.fill(password);
  await dialog.getByRole('button', { name: 'Reactivar cuenta' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(card).toContainText('Activa');
  const own = page.getByRole('article', { name: 'admin', exact: true });
  await expect(own.getByRole('button', { name: /Desactivar/ })).toHaveCount(0);
  await page.getByLabel('Buscar usuarios').fill('ana@');
  await expect(page.locator('.user-card')).toHaveCount(1);
  await page.getByLabel('Buscar usuarios').fill('');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath('usuarios.png'), fullPage: true });
  for (const width of [320, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
});

test('alumnado: el administrador cambia la contraseña compartida desde el panel', async ({ page }) => {
  await page.goto(`${origin}/#/acceso-equipo`);
  await page.getByLabel('Correo electrónico').fill('admin@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Usuarios', exact: true }).click();
  await page.getByRole('button', { name: 'Cambiar contraseña de las clases', exact: true }).click();
  const dialog = page.getByRole('dialog');
  const replacement = randomBytes(24).toString('base64url');
  await dialog.getByLabel('Nueva contraseña', { exact: true }).fill(replacement);
  await dialog.getByLabel('Repite la nueva contraseña').fill(password);
  await dialog.getByLabel('Tu contraseña actual de administrador').fill(password);
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Las nuevas contraseñas no coinciden');
  await dialog.getByLabel('Repite la nueva contraseña').fill(replacement);
  await dialog.getByLabel('Tu contraseña actual de administrador').fill('incorrect-password');
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Tu contraseña actual no es correcta');
  await dialog.getByLabel('Nueva contraseña', { exact: true }).fill(replacement);
  await dialog.getByLabel('Repite la nueva contraseña').fill(replacement);
  await dialog.getByLabel('Tu contraseña actual de administrador').fill(password);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('heading', { name: 'Acceso del alumnado' })).toBeVisible();
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain(replacement);
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.getByLabel('Contraseña de las clases').fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await page.getByLabel('Contraseña de las clases').fill(replacement);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page).toHaveURL(/#\/aula$/);
});

test('usuarios: cambiar mi contraseña cierra la sesión y permite entrar con la nueva', async ({ page }) => {
  await page.goto(`${origin}/#/acceso-equipo`);
  await page.getByLabel('Correo electrónico').fill('admin@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Usuarios', exact: true }).click();
  await page.getByRole('button', { name: 'Cambiar contraseña de admin', exact: true }).click();
  const dialog = page.getByRole('dialog');
  const replacement = randomBytes(24).toString('base64url');
  await dialog.getByLabel('Nueva contraseña', { exact: true }).fill(replacement);
  await dialog.getByLabel('Repite la nueva contraseña').fill(replacement);
  await dialog.getByLabel('Tu contraseña actual de administrador').fill(password);
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByLabel('Correo electrónico')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Usuarios del equipo' })).toHaveCount(0);
  await page.getByLabel('Correo electrónico').fill('admin@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill(replacement);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Usuarios', exact: true })).toBeVisible();
});
